#!/bin/bash
cat << EOF >> YYeTsFE/.env
SENTRY_ORG=$SENTRY_ORG
SENTRY_PROJECT=$SENTRY_PROJECT
SENTRY_AUTH_TOKEN=$SENTRY_AUTH_TOKEN


REACT_APP_SENTRY_DSN=$REACT_APP_SENTRY_DSN
REACT_APP_DOMAIN=$REACT_APP_DOMAIN
REACT_APP_GA=$REACT_APP_GA
# sourcemap
GENERATE_SOURCEMAP=$GENERATE_SOURCEMAP
REACT_APP_ADSENSE=$REACT_APP_ADSENSE
EOF
