name: Publish golang one key release
on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build binaries
        run: |
          npm install -g yarn
          make all
          ls yyetsweb/builds/

      - name: Release files
        uses: softprops/action-gh-release@v1
        with:
          name: "YYeTs"
          files: yyetsweb/builds/*
