{
 "title": "YYeTs",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Other",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "help", "type": "timeseries" },
    { "target": "database", "type": "timeseries" },
    { "target": "discuss", "type": "timeseries" }
   ]
  },
  {
   "title": "Resource",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "resource", "type": "timeseries" },
    { "target": "top", "type": "timeseries" },
    { "target": "home", "type": "timeseries" },
    { "target": "search", "type": "timeseries" },
    { "target": "backOld", "type": "timeseries" },
    { "target": "extra", "type": "timeseries" }
   ]
  },
  {
   "title": "User",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "user", "type": "timeseries" },
    { "target": "share", "type": "timeseries" },
    { "target": "me", "type": "timeseries" },
    { "target": "comment", "type": "timeseries" }
   ]
  },
  {
   "title": "Action",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "multiDownload", "type": "timeseries" },
    { "target": "download", "type": "timeseries" },
    { "target": "favorite", "type": "timeseries" },
    { "target": "unFavorite", "type": "timeseries" }
   ]
  }
 ]
}